services:
  openresty-manager:
   image: uusec/openresty-manager:latest
   #image: swr.cn-south-1.myhuaweicloud.com/uusec/openresty-manager:latest
   #ulimits:
     #nproc: 65535
     #nofile:
       #soft: 102400
       #hard: 102400
   container_name: openresty-manager
   restart: always
   network_mode: host
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/resolv.conf:/etc/resolv.conf:ro
     - om_acme:/opt/om/acme
     - om_data:/opt/om/data
     - om_conf:/opt/om/nginx/conf

volumes:
  om_acme:
  om_data:
  om_conf:
